; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = src
data_dir = datazip

[env:nodemcuv2]
platform = https://github.com/platformio/platform-espressif8266.git
board = nodemcuv2
framework = arduino
lib_deps =
	me-no-dev/ESPAsyncTCP
	bblanchon/ArduinoJson@6.21.2
	links2004/WebSockets@^2.7.3
	knolleary/PubSubClient@^2.8.0
	plerup/EspSoftwareSerial@^8.2.0
	milesburton/DallasTemperature@^4.0.6
board_build.filesystem = littlefs
extra_scripts = gzip_littlefs.py
monitor_speed = 76800
board_build.f_cpu = 160000000L
build_flags = 
	-DFILTER_6W_SPIKES=1
	-DBWC_DEBUGGING=BWC_DEBUG_OUTPUT_SERIAL
	-DBWC_SPRINKLE_YIELDS
	-DWEBSOCKETS_NETWORK_TYPE="NETWORK_ESP8266_ASYNC"
	-DWEBSOCKETS_SAVE_RAM
	-D PIO_FRAMEWORK_ARDUINO_MMU_CACHE16_IRAM48_SECHEAP_SHARED
	-DVTABLES_IN_FLASH
monitor_filters = 
	esp8266_exception_decoder
	default
upload_protocol = espota
upload_port = 192.168.90.167
upload_flags = 
	--auth=esp8266

[env:esp32s3-devkitc1u-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.filesystem = littlefs
board_build.flash_size = 16MB
board_build.partitions = default_8MB.csv
board_build.psram = true
board_build.arduino.memory_type = qio_opi
build_unflags = -std=gnu++11 -std=gnu++14 -std=c++11 -std=c++14
build_flags = 
	-std=gnu++17
	-DBOARD_HAS_PSRAM
	-DFILTER_6W_SPIKES=1
	-DBWC_DEBUGGING=BWC_DEBUG_OUTPUT_SERIAL
	-DBWC_SPRINKLE_YIELDS
upload_speed = 921600
; monitor_speed = 115200
monitor_speed = 76800
monitor_filters =
	esp32_exception_decoder
	default
extra_scripts = gzip_littlefs.py
lib_deps = 
	bblanchon/ArduinoJson@6.21.2
	links2004/WebSockets@^2.7.3
	knolleary/PubSubClient@^2.8.0
	me-no-dev/AsyncTCP@^3.3.2
	plerup/EspSoftwareSerial@^8.2.0
	milesburton/DallasTemperature@^4.0.6
upload_protocol = espota
upload_port = 192.168.90.163
upload_flags = 
	--auth=esp8266
